const { REGEXP_EMAIL } = require( './src/emails' );
const { REGEXP_URL_YOUTUBE } = require( './src/urls' );
const {
    REGEXP_DATETIME_DEFAULT_STRICT,
    REGEXP_DATETIME_HTML_STRICT,
    REGEXP_DATETIME_SQL_STRICT,
    REGEXP_DATETIME_FN_STRICT,
} = require( './src/datetimes-strict' );
const {
    REGEXP_DATETIME_DEFAULT,
    REGEXP_DATETIME_HTML,
    REGEXP_DATETIME_SQL,
    REGEXP_DATETIME_FN,
} = require( './src/datetimes' );
const {
    REGEXP_DATE_DEFAULT,
    REGEXP_DATE_HTML,
    REGEXP_DATE_SQL,
    REGEXP_DATE_FN,
} = require( './src/dates' );

const REGEXP = {
    //region Emails

    EMAIL: REGEXP_EMAIL,

    //endregion
    //region Urls

    URL_YOUTUBE: REGEXP_URL_YOUTUBE,

    //endregion
    //region Dates

    DATETIME_DEFAULT_STRICT: REGEXP_DATETIME_DEFAULT_STRICT,
    DATETIME_HTML_STRICT: REGEXP_DATETIME_HTML_STRICT,
    DATETIME_SQL_STRICT: REGEXP_DATETIME_SQL_STRICT,
    DATETIME_FN_STRICT: REGEXP_DATETIME_FN_STRICT,

    DATETIME_DEFAULT: REGEXP_DATETIME_DEFAULT,
    DATETIME_HTML: REGEXP_DATETIME_HTML,
    DATETIME_SQL: REGEXP_DATETIME_SQL,
    DATETIME_FN: REGEXP_DATETIME_FN,

    DATE_DEFAULT: REGEXP_DATE_DEFAULT,
    DATE_HTML: REGEXP_DATE_HTML,
    DATE_SQL: REGEXP_DATE_SQL,
    DATE_FN: REGEXP_DATE_FN,

    //endregion
}

module.exports = {
    REGEXP,
    REGEXP_EMAIL,
    REGEXP_URL_YOUTUBE,
    REGEXP_DATETIME_DEFAULT_STRICT,
    REGEXP_DATETIME_HTML_STRICT,
    REGEXP_DATETIME_SQL_STRICT,
    REGEXP_DATETIME_FN_STRICT,
    REGEXP_DATETIME_DEFAULT,
    REGEXP_DATETIME_HTML,
    REGEXP_DATETIME_SQL,
    REGEXP_DATETIME_FN,
    REGEXP_DATE_DEFAULT,
    REGEXP_DATE_HTML,
    REGEXP_DATE_SQL,
    REGEXP_DATE_FN,
};